# Generated by Django 5.1.6 on 2025-02-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='blacklist_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='domain_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
