# Generated by Django 5.1.6 on 2025-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_scamreport_blacklist_status_scamreport_domain_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='blacklist_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
