# Generated by Django 5.1.6 on 2025-02-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_scamreport_downvotes_scamreport_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Flagged', 'Flagged'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
